### ISSUE TITLE
Excessive Files

### ISSUE THREAD

**Issue by jim-low** [JEhew1227/CSA#1]
I have noticed that most of the files in this repository is dedicated to only one thing, which has caused the project to have more files than it needs to have.

Instead of creating files that only take care of a single task. give them a general task and provide the specifications inside of those generalized files.

Here is an example:
Instead of having files like corn.asm, apples.asm, bananas.asm and etc to hold the menus of these fruits/vegetables.

Have a file called menu.asm and then set all your menu variables in this file

Cheers, Jim

**Comment by JEhew1227** [comment]
The new one i not yet upload , in the new one i have add all the variable inside, if you want check , we will find a time i can show you but many line lah , better you don't have a headache XD
