### ISSUE TITLE
Improper Procedures

### ISSUE THREAD

**Issue by jim-low** [JEhew1227/CSA#2]
There seems to be too many procedures (*proc*) that are defined as "MAIN" in all the *.asm files. This will surely fail during compile time when you include all the necessary as there will be multiple declarations of the MAIN proc.

Suggestions: 
- appropriately name all *proc* according to their usage and purpose
- create a main file to store the MAIN *proc* and include other asm files in this file

**Comment by JEhew1227** [comment]
Actually that all is previous file, now I have all combine together become
4000++ lines maybe ,no worry?

Then why you don't want SMS me, want Email eh?
